server:
  port: 8081
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

## 微信公众号对接
#weixin:
#  config:
#    originalid: gh_80caf5976cca
#    token: b135
#    app-id: wx1e8a334fdf3411b6
#    app-secret: 34a5fa71160c81fc0398f0086262a967
#    template_id: SX_E-6LyYhsIzke6DbP1W-KaPJS6UcsbHGqNdEcnFHA

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/person_mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml


## 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
#alipay:
#  enabled: true
#  app_id: 9021000143684540
#  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCTgNCLfwvatZlBqaewdbT5RBqCZi1UfVsHTnfSO90yEs+slrMANcG6GtKUG/95R3hy6KWl6UzWM0/vIDFkfLcBnbWjbG8Cz+ishyppd+4qX650TFJRrsv/NpCwCXEQ+T73ULqKnmasY02E4ukMWHKrIMssWU27+MizUzmBd5x6HXJm1BZq5VWRpSCIBHBcEkLgGKvHG+4yLCDPFQwcJxLK7HDvpZ3z/8ml7QUbxm3ZdhOB1RBJIa7mWnZPrrrgEA+y2aBVVKjXdx4bYBGRItoVlPpmCRV5dI66QgNB2SvuxnI8BiBt1uWt6ECHMCQbZvnvj6Oye2dHuXpUtD7PHpdtAgMBAAECggEAP6dlV+25teaMfrOyNAp30OI89m0VvtJiCCMqvkUrTcKkcHyQPtT0B1Yv7c6vTy0yo5QWeCTYDdAS/MTNy+muKDpg+md++J20cU/bU6x30T19UZ7mH23phveLNQy+CG8nZx8lgVCeSmKIP4KUw8kfow4B39+iFi5knk6aEG8HzgJiPt/CJ+cGlrDndEUppcNSykB4hZAkU63DkqkoazkH+5fPyNLONmzzlO2/y/DvwY/Tf5kIrQ26O/LrLgD4DUmQkt9lavqh1ZPe4bygunMVUv33O62Gyaeyts1kNUM5AnUyZ1wt8ImcxW7Lj4UrQraeVSvuNKNEqeaQ8ayn+CG1WQKBgQDbLpWplcv0hL0yDBPiNaf1+VZc2QsRwglWusst67ftQRj1WV+jeW/q7bV0qVRop7+FZygml9W1BrnsVG3cMIDE8LcCix4ovOaliZyMNyE/sinIe3t7jJlYlf6qBTlZze4pHkZ+TkeZ3xcNqqrPE04dND+qR/f0moUyx0vczkENIwKBgQCsR9lTlM2l77W2IsG9m9fWx9hZ6xvnt9MRnrfx4doy+8nuB+cpX50V3RTjwvsQz+Lc0qxnSwbvqomcIXyFIEG9BeDcu2LBfcYI5KU/cdT/lepehrTBMul5PxK//FglpGHYb4jN8fF6H/8neLXS9bkog62ll50f+D/uMR7LuFP6LwKBgH8M6Notp9UsYJMzJw94NM1DZAlcEquPg2RP0Njki3AuzO3jiam0CejvM8DVKsWjf0QwALkmSE2wAXP5mNkLEImYUy1ZQPkyTqxkMWehyVcnykqZMYHzhSwxfjZF4vGoikYxc4FhlOWfyLg2Vt7D/QK2t7TYFOYn78/4cIQk1tZrAoGBAJxC0wE3f8vZf5TDM706RGxgeYEdegMTvdNGhgtT0mjZ7k8DRg1F1yJEk7T+XmDiXh/yykMqTxFFOmmuCdZp6pZ7ZXhwUmO0I9JfKO9B3XMxVBIG1p5CAnhh2CzgwkbqMYFxsMEziNY/fVwc5baCAD6aKP+AZBjiP4JZdVhMSYcrAoGANoQn/x4pPTmX+FFJIxBx6iFXPFCstABcuzwvneUmvAS6HPICmEsZvLfFZvTm/PDnyj27RI3viMDxjgEjNcOTvLt/aDicIWjjKl8Y+d/k8f/QvmzP365xzBnwVk3xh1F8dyy1bDV+QrJjTi8E9XuNWrS4PkA7LaNQA60veKWA1eI=
#  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmWXXp1C3A2GVxKAKH54pl13avtS+sD5E7Nx0RuX7mnaGByANrvGpmZcYxrEBa18frgkPPOdREs6TC5iir4aguE3b8rAsnPLO1BSyoyIZtVR1Y4G6O4q7dw6I1iKEQTsmz0h1R3qVA0aUYqOgYTQ8ejzJGAh2dMMb2YSo8xeIhJi1/BPuO7mli182iEHQ7iXKm6fViTLyPfYBRJOBP7+sI/fyOW38WyQGJlrYOvH44wnI9iDbBsNMmM/h82SYJFloWANq0wtfnHj93iuNr7x8AE0FV7JFB39ZtX563trH+gKtXFJ3L0sDEcPUnXeXGSKps/cz2X3QEXeiif9ZsDapbwIDAQAB
#  notify_url: http://jasper123.natapp1.cc/api/v1/alipay/alipay_notify_url
#  return_url: https://gaga.plus
#  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

#日志
logging:
  level:
    root: info
    com.cwb.dao: DEBUG
  config: classpath:logback-spring.xml

